In [7]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [19]:
df = pd.read_csv('Binance_BTCUSDT_d.csv')

In [20]:
df.head()
# Daily chart data

,unix,date,symbol,open,high,low,close,Volume BTC,Volume USDT,pct_chagnge
0,1.652400e+12,44694,BTC/USDT,29020.8,29300.0,28730.4,29189.7,13070.24,3.791286e+08,NaN
1,1.652310e+12,44693,BTC/USDT,29077.9,30257.0,26631.0,29020.7,964475.59,2.741261e+10,-0.01
2,1.652230e+12,44692,BTC/USDT,31002.1,32197.6,27651.0,29074.7,1101875.97,3.343266e+10,0.00
3,1.652140e+12,44691,BTC/USDT,30056.0,32650.0,29701.4,31002.1,863178.96,2.700279e+10,0.07
4,1.652050e+12,44690,BTC/USDT,34032.1,34243.3,30003.6,30056.6,1078779.71,3.458509e+10,-0.03

In [21]:
# !pip install ta-lib

In [22]:
import talib

In [23]:
df['sar'] = talib.SAR(df['high'], df['low'], acceleration=0.02, maximum=0.2)

In [24]:
df.head()

,unix,date,symbol,open,high,low,close,Volume BTC,Volume USDT,pct_chagnge,sar
0,1.652400e+12,44694,BTC/USDT,29020.8,29300.0,28730.4,29189.7,13070.24,3.791286e+08,NaN,NaN
1,1.652310e+12,44693,BTC/USDT,29077.9,30257.0,26631.0,29020.7,964475.59,2.741261e+10,-0.01,26631.00
2,1.652230e+12,44692,BTC/USDT,31002.1,32197.6,27651.0,29074.7,1101875.97,3.343266e+10,0.00,26631.00
3,1.652140e+12,44691,BTC/USDT,30056.0,32650.0,29701.4,31002.1,863178.96,2.700279e+10,0.07,26631.00
4,1.652050e+12,44690,BTC/USDT,34032.1,34243.3,30003.6,30056.6,1078779.71,3.458509e+10,-0.03,26992.14

In [16]:
df['position'] = np.where((df['close'] > df['sar']) & (df['close'].shift(1) < df['sar'].shift(1)) , 1, 0)
df['position'] = np.where((df['close'] < df['sar']) & (df['close'].shift(1) > df['sar'].shift(1)) , -1, df['position'])

Empty DataFrame
Columns: [unix, date, symbol, open, high, low, close, Volume BTC, Volume USDT, pct_chagnge, Unnamed: 10, sar]
Index: []